version: '3.3'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    ports:
      - 9042:9042
      - 7199:7199
  django:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - cassandra
    ports:
      - 9091:9091
    entrypoint: /srv/backend-entrypoint.sh
  vue:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 9092:9092
    command: npm run dev
