FROM node:9.11

LABEL maintainer="Moeen Zamani <moeenzdev@gmail.com>"

ADD frontend/package-lock.json /srv/frontend/package-lock.json
ADD frontend/package.json /srv/frontend/package.json

WORKDIR /srv/frontend

RUN npm install

COPY ./frontend/ /srv/frontend/
